/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3895c96c-f6f3-4543-af88-ff83dcf41ddc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_R6k5YitAi",
    "aws_user_pools_web_client_id": "16u09k5qchdspo07tfmqlftemq",
    "oauth": {}
};


export default awsmobile;
